#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true
#Kotlin
kotlin.code.style=official
kotlin.js.compiler=ir
#MPP
kotlin.mpp.enableCInteropCommonization=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
VERSION_NAME=0.1.0
POM_LICENSE_NAME=The Apache License, Version 2.0
GROUP=io.github.yourusername.klytics
POM_NAME=Klytics
POM_DESCRIPTION=A Kotlin Multiplatform analytics library.
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_INCEPTION_YEAR=2024
POM_ARTIFACT_ID=klytics
multiplatformLibrary=true
